### ISSUE TITLE
@VisibleForTesting?

### ISSUE THREAD

**Issue by manijshrestha** [zetaapps/utils#1]
This is great!!! This is going to be one of the goto dependency going forward :).

One note, since `@VisibleForTesting` is already part of Support annotation, should we reconsider its existence here?

**Comment by cdflynn** [comment]
Ah, yeah I'll remove that.

**Comment by manjunathc23** [comment]
👍

**Comment by manijshrestha** [comment]
👍

**Comment by cdflynn** [comment]
merged #3
